"""empty message

Revision ID: 0e70b3bb41e8
Revises: b4b5c49ff313
Create Date: 2025-08-02 09:56:07.405712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e70b3bb41e8'
down_revision: Union[str, None] = 'b4b5c49ff313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('end_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'end_at')
    op.drop_column('task', 'start_at')
    # ### end Alembic commands ###
